### ISSUE TITLE
Package libsecret-1 was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by DavidF-Beam** [waldekmastykarz/docker-spfx#49]
hi,

When I run the standard build before I even run GULP serve  I get the above error message.

When I try to do s auso to install it I get told that sudo dosnet exist , is teher a root password so I can do a su -  or is theer some other way to get round these issues

![image](https://user-images.githubusercontent.com/66625301/118293504-9f608700-b4d1-11eb-9f1e-faa6c410c30b.png)

![image](https://user-images.githubusercontent.com/66625301/118293557-ac7d7600-b4d1-11eb-8d00-2746692b93af.png)

Thanks David

**Comment by waldekmastykarz** [comment]
Which version of the image are you using? Do you have some additional information about how I could reproduce this issue?

**Comment by DavidF-Beam** [comment]
Hey, sure no problem.

This is my first run of the container after finding it online. its using the latest image. I've basically downloaded the image and started the yo creation. I've not made any changes and I'm basically following  through the readme to get it setup to start testing on. 

during the yo @microsoft/sharepoint command I start getting  warning about depreciated versions which ends with the error below. it starts after thnpm audit fix commands 

```
> keytar@7.7.0 build /usr/app/spfx/node_modules/keytar
> node-gyp rebuild
```


![image](https://user-images.githubusercontent.com/66625301/118456822-4c651a80-b6f1-11eb-8277-eaa06191f47d.png)
![image](https://user-images.githubusercontent.com/66625301/118457304-87674e00-b6f1-11eb-89c2-f4c99c84aa37.png)


Any help you could give me would be great, as using docker for this kind of development seems like a no brainer 

Thanks David 








I'm using docker for windows with WSL2, teh version of docker engine is 20.10.6  my windowws version is 1909 if that helps

**Comment by waldekmastykarz** [comment]
I wonder if that might've been a network glitch. I tried reproducing it, but it's working as expected for me. Would you mind giving it another try?

**Comment by DavidF-Beam** [comment]
yeah that's weird I tried it a couple of times before I raised the error and I got the same issue. I tried again yesterday and no error.  however I got a different issue this time

![image](https://user-images.githubusercontent.com/66625301/118613982-2f931a80-b7b7-11eb-97c8-5f5134d269d5.png)

on checking the notes I thought I might need to make the changes t the SPWebBuildRig.js  but on my file I don't have the information to change in it

![image](https://user-images.githubusercontent.com/66625301/118614209-6b2de480-b7b7-11eb-9da5-095e62acbe68.png)



![image](https://user-images.githubusercontent.com/66625301/118614608-db3c6a80-b7b7-11eb-9e5f-ca12eac4e7d7.png)

**Comment by waldekmastykarz** [comment]
Have you adjusted the hostname as mentioned in the docs @ https://github.com/waldekmastykarz/docker-spfx#cant-access-workbench-and-bundles-in-sharepoint-framework-160?

**Comment by DavidF-Beam** [comment]
hey, 

Yeah I made that change without it I couldnt even connect to the workbench 

![image](https://user-images.githubusercontent.com/66625301/118958666-88021d80-b959-11eb-92f2-9ca3595dd8c0.png)


I did notice an error on the gulp serve which I don't know if this happens all the time or if its unrelated. 

![image](https://user-images.githubusercontent.com/66625301/118959150-f34bef80-b959-11eb-8f12-e695a68dbe95.png)

**Comment by waldekmastykarz** [comment]
If I'm not mistaken, this is expected, because there is no browser installed inside the Docker container so when SPFx is trying to open the workbench it fails.

Have you tried to open the failing https://0.0.0.0:4321/... URL in the browser to see if you can access it?

**Comment by dannyjessee** [comment]
> yeah that's weird I tried it a couple of times before I raised the error and I got the same issue. I tried again yesterday and no error. however I got a different issue this time
> 
> ![image](https://user-images.githubusercontent.com/66625301/118613982-2f931a80-b7b7-11eb-97c8-5f5134d269d5.png)
> 
> on checking the notes I thought I might need to make the changes t the SPWebBuildRig.js but on my file I don't have the information to change in it
> 
> ![image](https://user-images.githubusercontent.com/66625301/118614209-6b2de480-b7b7-11eb-9da5-095e62acbe68.png)
> 
> ![image](https://user-images.githubusercontent.com/66625301/118614608-db3c6a80-b7b7-11eb-9e5f-ca12eac4e7d7.png)

I am experiencing this exact same issue as well with the 1.12.1 release. It appears that the generated manifest correctly uses https://localhost:4321 in all of the loaderConfig/internalModuleBaseUrls sections except the very last one, which happens to include all of the scriptResources for "hello-world-web-part." Its "internalModuleBaseUrls" array contains "https://0.0.0.0:4321/dist/" and so the workbench attempts to load "hello-world-web-part.js" from this URL, which fails. If I manually go to https://localhost:4321/dist/hello-world-web-part.js outside the workbench, the script loads just fine.

`[SPLoaderError.loadComponentError]:
Failed to load component "b0605d1f-279b-4de4-8f73-66b694df270c" (HelloWorldWebPart). Original error: Failed to load URL 'https://0.0.0.0:4321/dist/HelloWorldWebPartStrings_en-us.js' for resource 'HelloWorldWebPartStrings' in component 'b0605d1f-279b-4de4-8f73-66b694df270c' (HelloWorldWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://0.0.0.0:4321/dist/HelloWorldWebPartStrings_en-us.js' for resource 'HelloWorldWebPartStrings' in component 'b0605d1f-279b-4de4-8f73-66b694df270c' (HelloWorldWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
Error
    at SPLoaderError.SPError [as constructor] (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_en-us.js:38476:23)
    at new SPLoaderError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_en-us.js:52330:28)
    at Function.ff4n.ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_en-us.js:54879:21)
    at Function.ff4n.ErrorBuilder.buildLoadComponentError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/sp-webpart-workbench-assembly_en-us.js:54748:21)
    at https://localhost:4321/temp/workbench-packages/@microsoft_sp-webpart-workbench/local-workbench/chunk.systemjs-component-loader_en-us.js:1025:75`

Since there is no relevant section to change in SPWebBuildRig.js like there was with the 1.11 release, it seems like we're now missing a way to have the gulp bundle task write the proper debugBasePath into this one URL within the manifest.

**Comment by waldekmastykarz** [comment]
Thanks for such a thorough notes @dannyjessee. It would be good to share this with the SPFx team by creating an issue at https://github.com/SharePoint/sp-dev-docs/issues and explaining how it's blocking you. Hopefully they'll be able to address this in the future versions.

**Comment by shurick81** [comment]
Is there still an issue after applying the workarounds described in Readme, @dannyjessee, @DavidF-Beam?

**Comment by dannyjessee** [comment]
> Is there still an issue after applying the workarounds described in Readme, @dannyjessee, @DavidF-Beam?

No further issues here. I just closed [the original issue](https://github.com/SharePoint/sp-dev-docs/issues/7076) I submitted about this last year. Thanks!
