### ISSUE TITLE
Issues when adding new SPFx components to existing SPFx projects

### ISSUE THREAD

**Issue by JonasBjerke89** [waldekmastykarz/docker-spfx#9]
Hi,

We are using your Docker images when developing SPFx. It normally works like charm, but we are experiencing some issues in the following scenario:
We run a Docker image (say 1.4.0) and creates a new SPFx solution with a webpart. Everything works as expected and we can continue our development process.

Now, a few weeks/months later, we need to add another webpart to that project. There is now image 1.4.1 available, but we would like to keep it in version 1.4.0. So we once again start Docker with the 1.4.0 image and running the yo @microsoft/sharepoint command. This is where it goes wrong. The wizard works, but we expect it to just add the new webpart - not going out using npm and downloading packages again. Here's a sceenshot of some of it:
![image](https://user-images.githubusercontent.com/21952399/38859762-0712bbac-422f-11e8-8e85-68b78a371e6d.png)

After a few minutes it completes, but with errors:
![image](https://user-images.githubusercontent.com/21952399/38859836-2abc6526-422f-11e8-828a-508224b3bae3.png)

If we run gulp build we get:
![image](https://user-images.githubusercontent.com/21952399/38859891-3e765cc0-422f-11e8-83a3-b26be1eb19c2.png)

That's strange. If we run npm outdated we get:
![image](https://user-images.githubusercontent.com/21952399/38859937-58f930fe-422f-11e8-877b-88c8ac0f9050.png)

.. thats scares me. Now the solution wants 1.4.1 - not 1.4.0, which was the Docker image that we are using for this. Any advice will be greatly appreciated. Further investigations shows me, that npm-shrinkwrap.json doesn't include the microsoft/sp-build-web package for example. Is that normal?

Please let me know, if you need more information.

**Comment by JonasBjerke89** [comment]
*** UPDATE ***
If we delete the node_modules folder and running the npm-install again, the solution works again and npm outdated shows this: 
 
![image](https://user-images.githubusercontent.com/21952399/38868691-34f3bac6-4248-11e8-970e-e9d75ea21fa3.png)

The current version is still 1.4.0, but it still wants 1.4.1.

**Comment by waldekmastykarz** [comment]
Thanks for reaching out and great to hear you find the image useful. You mentioned a couple of things, so let me clarify them one by one 🙂 

> The wizard works, but we expect it to just add the new webpart - not going out using npm and downloading packages again. Here's a sceenshot of some of it:

If I'm not mistaken, running npm install after adding a new artifact is a part of the SharePoint Framework Yeoman generator. It might be required in scenarios where you for example initially created a project with a web part and then added an extension to it, that might require additional packages which you didn't have yet.

If you use a lock file, running npm install shouldn't matter, because each time you run it, you will get the exact set of versions specified in the lock file. When you work with npm@5, it creates a lock file for you automatically. In older versions of the SharePoint Framework, you would have to create it yourself using the `npm shrinkwrap` command. This isn't specific to using the SPFx Docker image, but rather working with npm in general.

> Now the solution wants 1.4.1 - not 1.4.0, which was the Docker image that we are using for this.

When you run `npm outdated` it compares the packages you have installed with the latest version of the package available on the internet in the npm registry. The Docker image doesn't play any role in here. npm will always try to update you to the latest version of each package available on the internet, no matter if it's compatible with your setup or not, so you have to use it with caution.

The Docker image I provided doesn't contain all SharePoint Framework packages inside. It only has the specific version of the SharePoint Framework Yeoman generator. All other packages are downloaded from the internet whenever you scaffold a new project.

Hope this helps and please let me know if I can clarify anything else.

**Comment by JonasBjerke89** [comment]
Thanks for your clarification. I know that Docker - and your images - is properly not to blame, but I don't have much experience with Docker yet. A few notes to your clarification:

> If I'm not mistaken, running npm install after adding a new artifact is a part of the SharePoint Framework Yeoman generator. It might be required in scenarios where you for example initially created a project with a web part and then added an extension to it, that might require additional packages which you didn't have yet.
I agree, but it seems wrong that it downloads additional packages when adding a webpart to an existing solution, that already contains a webpart? Doesn't it? If the asset already exists, we could --skip-install but it seems wrong to me :-)

> When you run npm outdated it compares the packages you have installed with the latest version of the package available on the internet in the npm registry. The Docker image doesn't play any role in here. npm will always try to update you to the latest version of each package available on the internet, no matter if it's compatible with your setup or not, so you have to use it with caution.
Yes, it compares with the npm repo for latest/newer versions, but what about the "Wanted" column? To my understanding this shows the version, that the solution expects - not necessary the latest one. This is what scares me:
The solution is 1.4.0. After adding another webpart, it suddently wants 1.4.1 and some packages are even missing. If I delete the node_modules and running npm install, it all works again and the current version is 1.4.0 (npm outdated again after install).

Thanks again for your time :-)

**Comment by waldekmastykarz** [comment]
I suspect that the reason why in the `wanted` column, you see `1.4.1` for a project created using v1.4.0 is how the version is stored in the `package.json` file. In my case, if I look at package.json for a project created v1.4.0, I'm seeing:

```json
{
  "name": "spfx-140-1",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@types/webpack-env": ">=1.12.1 <1.14.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.0",
    "@microsoft/sp-module-interfaces": "~1.4.0",
    "@microsoft/sp-webpart-workbench": "~1.4.0",
    "gulp": "~3.9.1",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "ajv": "~5.2.2"
  }
}
```

If I now run `npm outdated`, I get:

```text
Package                              Current  Wanted  Latest  Location
@microsoft/sp-build-web                1.4.0   1.4.1   1.4.1  spfx-140-1
@microsoft/sp-core-library             1.4.0   1.4.1   1.4.1  spfx-140-1
@microsoft/sp-lodash-subset            1.4.0   1.4.1   1.4.1  spfx-140-1
@microsoft/sp-module-interfaces        1.4.0   1.4.1   1.4.1  spfx-140-1
@microsoft/sp-office-ui-fabric-core    1.4.0   1.4.1   1.4.1  spfx-140-1
@microsoft/sp-webpart-base             1.4.0   1.4.1   1.4.1  spfx-140-1
@microsoft/sp-webpart-workbench        1.4.0   1.4.1   1.4.1  spfx-140-1
@types/chai                            3.5.2   3.5.2   4.1.2  spfx-140-1
@types/mocha                          2.2.44  2.2.48   5.0.0  spfx-140-1
@types/webpack-env                    1.13.2  1.13.6  1.13.6  spfx-140-1
ajv                                    5.2.5   5.2.5   6.4.0  spfx-140-1
```

If you look closely, the version of each of the SPFx packages is expressed like `~1.4.0` which is a range. And `1.4.1`, being a patch update to `1.4.0` matches that range, which is why npm says it wants that version.

I'd say, that the most important part is, that the current version of the packages in your solution, matches the version of SPFx you want to use.

**Comment by JonasBjerke89** [comment]
Ah, ranges. Of course! 

I thought that shrinkwrap (and package-lock.json i npm5) included _all_ packages in the specific version, but as stated earlier packages like microsoft/sp-build-web is not included for some reason.

Well, that too explains why the "yo microsoft/sharepoint" was looking for updated packages (1.4.1 versions) when adding a new asset to an 1.4.0 solution. But I still can't get my head around WHY the solution breaks afterwards? The error messages is not quite friendly to me :-)

A temporary solution is either to use --skip-install or delete the node_modules folder and run npm-install again, if the solution breaks.

Thanks for your time discussing this behaviour.

**Comment by waldekmastykarz** [comment]
If you have a lock file, npm should honor it and should install exactly the version you have listed there no matter what package.json or npm outdated say.

When starting the SPFx Docker container, do you always apply the label at the end or do you sometimes start it without the label. In other words: is there a chance you might be running container with SPFx v1.4.1 while you're thinking you are in SPFx v1.4.0?

**Comment by JonasBjerke89** [comment]
> When starting the SPFx Docker container, do you always apply the label at the end or do you sometimes start it without the label. In other words: is there a chance you might be running container with SPFx v1.4.1 while you're thinking you are in SPFx v1.4.0?

We always start it with the version label. I have made a simple PowerShell module for our team, when using Docker:
![image](https://user-images.githubusercontent.com/21952399/39031412-3f95f01c-4468-11e8-80ee-59053ccca9eb.png)
Our team just opens VSCode and opens the SPFx solution folder. Using the Integrated Terminal they just type "Run-Docker -version 1.4.0".

The idea was to abstract away the port mapping and labeling and making it easy to use.

**Comment by waldekmastykarz** [comment]
Sounds like a very good idea!
